### ISSUE TITLE
Windows Builds Not Working For Most Subsystems

### ISSUE THREAD

**Issue by ccoenen** [novaquark/sysinfo_influxdb#23]
I tried four builds from gobuild on Win8.1 x64. All of them failed with virtually the same error messages (quoted in full). The error messages only differ in their Hex-IDs, so i only included the x64 build of 0.5.

I _can_ get `sysinfo_influxdb --help`, so the binary works partly.

0.5 x64

    λ sysinfo_influxdb.exe
    panic: Not Implemented
    
    goroutine 20 [running]:
    runtime.panic(0x640560, 0xc082000ab0)
            c:/go/src/pkg/runtime/panic.c:279 +0x11f
    github.com/cloudfoundry/gosigar.notImplemented(0x0, 0x0)
            /gopath/src/github.com/cloudfoundry/gosigar/sigar_windows.go:98 +0x7a
    github.com/cloudfoundry/gosigar.(*Cpu).Get(0x3c3e88, 0x0, 0x0)
            /gopath/src/github.com/cloudfoundry/gosigar/sigar_windows.go:44 +0x37
    main.cpu(0xc082000972, 0x7, 0xc08203e0a0, 0x0, 0x0)
            /gopath/src/github.com/novaquark/sysinfo_influxdb/main.go:341 +0x1b0
    created by main.main
            /gopath/src/github.com/novaquark/sysinfo_influxdb/main.go:187 +0xa09
    
    goroutine 16 [chan receive]:
    main.main()
            /gopath/src/github.com/novaquark/sysinfo_influxdb/main.go:191 +0xa86
    
    goroutine 17 [syscall]:
    runtime.goexit()
            c:/go/src/pkg/runtime/proc.c:1445
    
    goroutine 19 [finalizer wait]:
    runtime.park(0x41e8e0, 0x8a38c0, 0x8a19a9)
            c:/go/src/pkg/runtime/proc.c:1369 +0xac
    runtime.parkunlock(0x8a38c0, 0x8a19a9)
            c:/go/src/pkg/runtime/proc.c:1385 +0x42
    runfinq()
            c:/go/src/pkg/runtime/mgc0.c:2644 +0xdd
    runtime.goexit()
            c:/go/src/pkg/runtime/proc.c:1445
    
    goroutine 21 [runnable]:
    main.cpus(0xc082000972, 0x7, 0xc08203e0a0, 0x1, 0xc082000972)
            /gopath/src/github.com/novaquark/sysinfo_influxdb/main.go:351
    created by main.main
            /gopath/src/github.com/novaquark/sysinfo_influxdb/main.go:187 +0xa09
    
    goroutine 22 [runnable]:
    main.mem(0xc082000972, 0x7, 0xc08203e0a0, 0x1, 0xc082000972)
            /gopath/src/github.com/novaquark/sysinfo_influxdb/main.go:368
    created by main.main
            /gopath/src/github.com/novaquark/sysinfo_influxdb/main.go:187 +0xa09
    
    goroutine 23 [runnable]:
    main.swap(0xc082000972, 0x7, 0xc08203e0a0, 0x1, 0xc082000972)
            /gopath/src/github.com/novaquark/sysinfo_influxdb/main.go:386
    created by main.main
            /gopath/src/github.com/novaquark/sysinfo_influxdb/main.go:187 +0xa09
    
    goroutine 24 [runnable]:
    main.uptime(0xc082000972, 0x7, 0xc08203e0a0, 0x1, 0xc082000972)
            /gopath/src/github.com/novaquark/sysinfo_influxdb/main.go:404
    created by main.main
            /gopath/src/github.com/novaquark/sysinfo_influxdb/main.go:187 +0xa09
    
    goroutine 25 [runnable]:
    main.load(0xc082000972, 0x7, 0xc08203e0a0, 0x1, 0xc082000972)
            /gopath/src/github.com/novaquark/sysinfo_influxdb/main.go:422
    created by main.main
            /gopath/src/github.com/novaquark/sysinfo_influxdb/main.go:187 +0xa09
    
    goroutine 26 [runnable]:
    main.network(0xc082000972, 0x7, 0xc08203e0a0, 0x1, 0xc082000972)
            /gopath/src/github.com/novaquark/sysinfo_influxdb/main.go:440
    created by main.main
            /gopath/src/github.com/novaquark/sysinfo_influxdb/main.go:187 +0xa09
    
    goroutine 27 [runnable]:
    main.disks(0xc082000972, 0x7, 0xc08203e0a0, 0x1, 0xc082000972)
            /gopath/src/github.com/novaquark/sysinfo_influxdb/main.go:497
    created by main.main
            /gopath/src/github.com/novaquark/sysinfo_influxdb/main.go:187 +0xa09
    panic during panic
    
    goroutine 21 [running]:
    runtime.panic(0x640560, 0xc082000ad0)
            c:/go/src/pkg/runtime/panic.c:276 +0xf6
    github.com/cloudfoundry/gosigar.notImplemented(0x0, 0x0)
            /gopath/src/github.com/cloudfoundry/gosigar/sigar_windows.go:98 +0x7a
    github.com/cloudfoundry/gosigar.(*CpuList).Get(0x3f3ec8, 0x0, 0x0)
            /gopath/src/github.com/cloudfoundry/gosigar/sigar_windows.go:48 +0x37
    main.cpus(0xc082000972, 0x7, 0xc08203e0a0, 0x0, 0x0)
            /gopath/src/github.com/novaquark/sysinfo_influxdb/main.go:359 +0x1b7
    created by main.main
            /gopath/src/github.com/novaquark/sysinfo_influxdb/main.go:187 +0xa09
    stack trace unavailable

After that, i tried querying only some subsystems:

    λ sysinfo_influxdb.exe -c="cpu"
    panic: Not Implemented
    [...]
    
    λ sysinfo_influxdb.exe -c="cpus"
    panic: Not Implemented
    [...]
    
    λ sysinfo_influxdb.exe -c="mem"
    #0: PC.mem
    | free  | used  | actualfree    | actualused    | total |
    | 0     | 0     | 0     | 0     | 8469200896    |
    (total is correct, at least something :) )
    
    λ sysinfo_influxdb.exe -c="swap"
    panic: Not Implemented
    [...]
    
    λ sysinfo_influxdb.exe -c="uptime"
    #0: PC.uptime
    | length        |
    | 0     |
    (errr.... no.)
    
    λ sysinfo_influxdb.exe -c="load"
    #0: PC.load
    | one   | five  | fifteen       |
    | 0     | 0     | 0     |
    (well, that was kind-of expected)
    
    λ sysinfo_influxdb.exe -c="network"
    (did not return, had to Ctrl+C kill it)
    
    λ sysinfo_influxdb.exe -c="disks"
    (did not return, had to Ctrl+C kill it)

There was no difference, whether i ran sysinfo_influxdb with or without administrator privileges. The verbose flag did not return anything for the last two commands.

**Comment by nemunaire** [comment]
Hi,

I read from https://github.com/cloudfoundry/gosigar#supported-platforms that Windows is not supported yet :(

I'll indicate that in the README file.
