### ISSUE TITLE
404 error for gobuild website download link

### ISSUE THREAD

**Issue by trkrameshkumar** [novaquark/sysinfo_influxdb#28]
Hi Guys,

I got 404 error, when i try to download fro the following link 

http://gobuild.io/github.com/novaquark/sysinfo_influxdb?tag=branch:master

**Comment by BarthV** [comment]
gobuild.io seems have been lost in the interwebz blackhole :-/
You'll have to build it by yourself , and maybe we're gonna have to remove this link from the readme.

**Comment by nemunaire** [comment]
I just remove link from the README since we are no news from gobuild for a long time :(
